name: "productive-box"
author: "maxam2017"
description: "Are you an early 🐤 or a night 🦉? Let's check out in gist"
branding:
  icon: "activity"
  color: "blue"
runs:
  using: "node16"
  main: "dist/index.js"
